import { LegalShell, SUPPORT_EMAIL } from "../legal/_shared";

export const metadata = { title: "AI Policy — Inkling" };

export default function AiPolicy() {
  return (
    <LegalShell title="AI Policy" updated="July 27, 2026">
      <p>
        Inkling is an AI product from top to bottom, so it's worth being direct about how that AI
        works, what it does with your input, and where its limits are.
      </p>

      <h2>How Inkling uses AI</h2>
      <p>
        When you search a book or paste a passage, Anthropic's Claude model reads the text to
        identify characters and extract the descriptive detail a portrait artist would need —
        appearance, era, personality. That description is then handed to OpenAI's image model,
        which paints an original portrait from scratch. Both steps happen live, every time — there
        is no library of pre-made portraits.
      </p>

      <h2>Does AI train on my data?</h2>
      <p>
        Inkling calls Anthropic's and OpenAI's developer APIs — not their consumer chat products.
        Per both companies' standard API data-usage policies, input and output data sent through
        their APIs is not used to train their models by default. Provider policies can change, so
        if this matters to you, we'd encourage checking their current terms directly:
      </p>
      <ul>
        <li><a href="https://www.anthropic.com/legal/commercial-terms" target="_blank" rel="noopener noreferrer">Anthropic's API terms</a></li>
        <li><a href="https://openai.com/policies/api-data-usage-policies" target="_blank" rel="noopener noreferrer">OpenAI's API data usage policy</a></li>
      </ul>

      <h2>Content ownership</h2>
      <p>
        Portraits generated by Inkling are original AI interpretations of the text you provided —
        not reproductions of an illustrator's artwork, a film adaptation, or a real person. The
        legal treatment of AI-generated content's copyright status is still evolving and varies by
        jurisdiction, so we can't make a legal guarantee about exclusive ownership. In practice,
        you're free to use portraits generated in your own session for personal purposes.
      </p>

      <h2>AI limitations and accuracy</h2>
      <p>
        Character descriptions are the AI's interpretation of a book or passage, not a verified or
        "canonical" reading — they can miss detail, take creative liberties, or occasionally get
        something wrong. Treat every result as an artistic interpretation, not a substitute for
        reading the original text. Quality and availability also depend on the underlying
        third-party AI providers and may change without notice.
      </p>

      <h2>Responsible use</h2>
      <p>
        Please don't use Inkling to try to generate the likeness of a real, living person. It's
        built for fictional characters from books.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about how AI is used in Inkling can be sent to{" "}
        <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>.
      </p>
    </LegalShell>
  );
}
