import { PageShell } from "../_shared/PageShell";

export const metadata = { title: "Gallery — Inkling" };

const REAL_GALLERY = [
  { name: "Elizabeth Bennet", book: "Pride and Prejudice", style: "Painterly", src: "/hero/elizabeth.png" },
  { name: "Heathcliff", book: "Wuthering Heights", style: "Painterly", src: "/hero/heathcliff.png" },
  { name: "Jane Eyre", book: "Jane Eyre", style: "Painterly", src: "/hero/jane-eyre.png" },
  { name: "Sherlock Holmes", book: "The Adventures of Sherlock Holmes", style: "Ink Sketch", src: "/gallery/holmes.png" },
  { name: "Jay Gatsby", book: "The Great Gatsby", style: "Impressionist", src: "/gallery/gatsby.png" },
  { name: "Captain Ahab", book: "Moby-Dick", style: "Realism", src: "/gallery/ahab.png" },
];

export default function Gallery() {
  return (
    <PageShell
      title="Gallery"
      subtitle="A few real portraits generated by Inkling — every one of them created fresh from the text, on demand."
      wide
    >
      <div className="gallery-grid">
        {REAL_GALLERY.map((g) => (
          <figure key={g.name} className="gallery-card">
            <img src={g.src} alt={`AI-generated portrait of ${g.name} from ${g.book}`} />
            <figcaption>
              <div className="gallery-name">{g.name}</div>
              <div className="gallery-meta">
                {g.book} · {g.style}
              </div>
            </figcaption>
          </figure>
        ))}
      </div>
      <p className="gallery-note">
        Want to see your own? Head back to Inkling and search a book — every portrait is generated
        the moment you ask for it.
      </p>
    </PageShell>
  );
}
