import { LegalShell, SUPPORT_EMAIL } from "../legal/_shared";

export const metadata = { title: "Terms of Service — Inkling" };

export default function TermsOfService() {
  return (
    <LegalShell title="Terms of Service" updated="July 27, 2026">
      <p>
        These terms govern your use of Inkling. By using the app, you agree to them. This is an
        independent, actively-developed project rather than a large formal company, so treat this
        as a good-faith, plain-language agreement rather than dense legal boilerplate.
      </p>

      <h2>What Inkling does</h2>
      <p>
        Inkling reads a book title, character name, or a passage of text you provide, and
        generates an original AI illustration and description of the character based on that
        text. Every result is generated fresh — nothing is pre-made or reused between users.
      </p>

      <h2>Acceptable use</h2>
      <ul>
        <li>Use Inkling for personal, non-commercial exploration unless we've agreed otherwise with you directly.</li>
        <li>Don't submit the name or description of a real, living person in an attempt to generate their likeness.</li>
        <li>Don't use Inkling to generate unlawful, infringing, hateful, or otherwise harmful content.</li>
        <li>Don't attempt to abuse, overload, or reverse-engineer the service.</li>
      </ul>

      <h2>Content and ownership</h2>
      <p>
        Portraits are original interpretations generated by AI models from the text you provide,
        not reproductions of any existing illustration, film adaptation, or photograph. See our{" "}
        <a href="/ai-policy">AI Policy</a> for more on how generated content is created and what
        you can do with it.
      </p>

      <h2>No warranty</h2>
      <p>
        Inkling is provided "as is." Generated descriptions and portraits are AI interpretations
        and may contain inaccuracies. We don't guarantee uninterrupted availability, and results
        depend in part on third-party AI providers outside our control.
      </p>

      <h2>Limitation of liability</h2>
      <p>
        To the fullest extent permitted by law, Inkling and its operator are not liable for
        indirect, incidental, or consequential damages arising from your use of the service.
      </p>

      <h2>Third-party services</h2>
      <p>
        Inkling relies on Anthropic's and OpenAI's APIs to function. Your use of Inkling is also
        subject to those providers' own terms of service.
      </p>

      <h2>Changes</h2>
      <p>
        We may update these terms as the product changes. Continued use of Inkling after an
        update means you accept the revised terms.
      </p>

      <h2>Termination</h2>
      <p>We may suspend or restrict access for anyone who misuses the service.</p>

      <h2>Contact</h2>
      <p>
        Questions about these terms can be sent to{" "}
        <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>.
      </p>
    </LegalShell>
  );
}
